library("bitops")
library("RCurl")
library("ggplot2")
library("plyr")
library("tidyr")
library("dplyr")
library("jsonlite")

#install.packages("devtools")
#devtools::install_github("rstudio/EDAWR")
require(EDAWR)
require(grid)